tango_with_django_project/rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'


urlpatterns = [
path('', views.cover, name='cover'),
path('bookshelf/', views.bookshelf, name='bookshelf'),
path('bookshelf_user/', views.bookshelf_user, name='bookshelf_user'),
path('index/<slug:source_title_slug>/', views.index, name='index'),
path('about/', views.about, name='about'),
path('contact_us/', views.contact_us, name='contact_us'),
path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
path('add_category/', views.add_category, name='add_category'),
path('category/<slug:category_name_slug>/add_vocabulary/', views.add_vocabulary, name='add_vocabulary'),
path('suggest/', views.CategorySuggestionView.as_view(), name='suggest'),
# path('register/', views.register, name='register'),
# path('login/', views.user_login, name='login'),
path('restricted/', views.restricted, name='restricted'),
path('sentence/', views.show_sentence, name='show_sentence'),
# path('kanshu/', views.kanshu, name='kanshu'),
path('like_category/', views.like_category, name='like_category'),
path('bookmark/', views.bookmark, name='bookmark'),
path('add_word2dict/', views.add_word2dict, name='add_word2dict'),
path('del_word2dict/', views.del_word2dict, name='del_word2dict'),
path('words_in_sent/', views.words_in_sent, name='words_in_sent'),
path('learnt/', views.learnt, name='learnt'),
path('edit/', views.edit, name='edit'),
path('useredit/', views.useredit, name='useredit'),
# path('next_kanshu/', views.next_kanshu, name='next_kanshu'),
path('kanshu_sentence/<slug:source_title_slug>/', views.kanshu_sentence, name='kanshu_sentence'),
path('kanshu_sentence2/<slug:source_title_slug>/', views.mother_text_helper_sentence, name='mother_text_helper_sentence'),
path('kanshu_carousel/<slug:source_title_slug>/', views.kanshu_carousel, name='kanshu_carousel'),
path('kanshu_carousel2/<slug:source_title_slug>/', views.mother_text_helper, name='mother_text_helper'),
# path('personal_kanshu/', views.personal_kanshu, name='personal_kanshu'),
path('personal_kanshu/<slug:source_title_slug>/', views.personal_kanshu_source, name='personal_kanshu_source'),

path('personal_kanshu_source_delete/<slug:source_title_slug>/', views.personal_kanshu_source_delete, name='personal_kanshu_source_delete'),
path('personal_kanshu_index_delete/', views.personal_kanshu_index_delete, name='personal_kanshu_index_delete'),

path('personal_kanshu_index/', views.personal_kanshu_index, name='personal_kanshu_index'),
path('kanshu_dashboard/', views.kanshu_dashboard, name='kanshu_dashboard'),
path('register_profile/', views.register_profile, name='register_profile'),
path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
# path('logout/', views.user_logout, name='logout'),
]

tango_with_django_project/rango/views.py
from django.template import RequestContext
from django.shortcuts import render, redirect
from rango.forms import CategoryForm, VocabForm, SentenceForm, ContactForm, EditForm, UserEditForm, UserVocabForm
from rango.forms import UserForm, UserProfileForm, UserUploadForm
from rango.edit import editword, usereditword
from django.template.loader import render_to_string
from django.http import HttpResponse
from rango.models import HSK, Category, Vocab, Sentence, Source, MotherText, UserSource, UserPrevious, UserVocab, UserCategory, UserSentence, UserBookmark, UserDictionary
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from datetime import datetime
from googletrans import Translator
from rango.kanshu import run_kanshu
from rango.user_kanshu import doc_process, binfile_to_db, run_user_kanshu
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from rango.models import UserProfile
from django.views import View
from django.utils.decorators import method_decorator
from django.core.mail import send_mail

import json
from django.http import JsonResponse
import string
from django.core.files.storage import FileSystemStorage
def useredit(request):
    user= request.user
    delete_session(request, 'result_list')
    delete_session(request, 'sides')
    form = UserVocabForm()
    if request.method == 'POST':
        form = UserVocabForm(request.POST, current_user=request.user)
        if form.is_valid():
            newword = form.save(commit=False)
            print('user.id: ' + str(user.id))
            print('newword.source.id: ' + str(newword.source.id))
            print('newword.chinese: ' + str(newword.chinese))

            try:

                v = UserVocab.objects.get(user_id=user.id, source_id=newword.source.id, chinese=newword.chinese)
                print(str(v))
                frequency = v.frequency
                v.delete()

                print('deleted v')
            except:
                print('editing word not found')
                frequency = 1
            newword.user = user
            pinyin = usereditword(user, newword.source, newword.chinese, newword.category)

            newword.pinyin = pinyin
            newword.frequency = frequency


            newword.save()
            return redirect(reverse('rango:personal_kanshu_index'))
        else:

            print(form.errors)

    return render(request, 'rango/useredit.html', {'form': form})


def edit(request):
    s = source_helper(request.user)
    delete_session(request, 'result_list')
    delete_session(request, 'sides')
    form = EditForm()
    if request.method == 'POST':
        form = EditForm(request.POST)
        if form.is_valid():
            word = form.cleaned_data['word']
            print('word: '+ word)
            tag = form.cleaned_data['tag']
            print('tag: ' + tag)
            english = form.cleaned_data['english']
            print('english: ' + english)
            source = s['title']
            print('source: ' + source)
            words = {'word':word, 'tag':tag, 'english': english}
            editword(s, words)
            return redirect(reverse('rango:kanshu_carousel'))
        else:

            print(form.errors)

    return render(request, 'rango/edit.html', {'form': form})


def contact_us(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # send email code goes here
            sender_name = form.cleaned_data['name']
            sender_email = form.cleaned_data['email']

            message = "{0} has sent you a new message:\n\n{1}".format(sender_name, form.cleaned_data['message'])
            send_mail('New Enquiry', message, sender_email, ['patelpriyesh@hotmail.com'])
            return HttpResponse('<h1>Thanks for contacting me! Click back button</h1>')
    else:
        form = ContactForm()

    return render(request, 'rango/contact_us.html', {'form': form})


def cover(request):
    context_dict = {}
    s = source_helper(request.user)
    context_dict['title'] = s['title']
    # Render the response and send it back!
    return render(request, 'rango/cover.html', context=context_dict)

# hgjiyhkhjkhjklh
def addremovebook(request, source_title_slug):

    s = Source.objects.filter(slug=source_title_slug)

    for i in r:

        s = Source.objects.get(title=i['title'])
        word_count=len(list(Vocab.objects.filter(source=s).values('chinese')))

        print(i['title'])
        title.append(i['title'])
        text.append(i['type'])
        author.append(i['author'])
        content.append((i['title'], i['type'], i['author'], i['slug'], i['picture'], str(word_count)))

    context_dict = {}
    s = source_helper(request.user)
    context_dict['title'] = s['title']
    # Render the response and send it back!

    def add_vocab(category, chinese, english, pinyin, learnt=0, score=0, previous=0, frequency=0):
        p = Vocab.objects.get_or_create(category=category, chinese=chinese, english=english, pinyin=pinyin)[0]
        p.score = score
        p.frequency = frequency
        p.previous = previous
        p.learnt = learnt
        p.save()
        return p

    return render(request, 'rango/cover.html', context=context_dict)



def bookshelf(request):
    context_dict = {}
    r = list(Source.objects.filter(language="Mandarin").values('title', 'type', 'author', 'picture'))

    title=[]
    text=[]
    author=[]
    content=[]

    for i in r:

        s = Source.objects.get(title=i['title'])
        word_count=len(list(Vocab.objects.filter(source=s).values('chinese')))

        print(i['title'])
        title.append(i['title'])
        text.append(i['type'])
        author.append(i['author'])
        content.append((i['title'], i['type'], i['author'], i['picture'], str(word_count)))

    context_dict['titles'] = title
    context_dict['texts'] = text
    context_dict['authors'] = author
    context_dict['contents'] = content
    print(content)
    # Render the response and send it back!
    return render(request, 'rango/bookshelf.html', context=context_dict)

@login_required
def bookshelf_user(request):
    context_dict = {}
    r = list(Source.objects.filter(language="Mandarin").values('title', 'slug', 'language', 'type', 'author', 'picture'))
    print(r)
    title=[]
    text=[]
    author=[]
    content=[]

    for i in r:

        s = Source.objects.get(title=i['title'])
        word_count=len(list(Vocab.objects.filter(source=s).values('chinese')))

        title.append(i['title'])
        text.append(i['type'])
        author.append(i['author'])
        content.append((i['title'], i['type'], i['author'], i['picture'], i['slug'], str(word_count)))

    context_dict['titles'] = title
    context_dict['texts'] = text
    context_dict['authors'] = author
    context_dict['contents'] = content
    print(context_dict)
    # Render the response and send it back!
    return render(request, 'rango/bookshelf_user.html', context=context_dict)


@login_required
def personal_kanshu_source(request, source_title_slug):
    context_dict = {}
    result_list = []

    user = request.user
    source = UserSource.objects.get(user=user, slug=source_title_slug)
    print('source_title_slug: ' + source_title_slug)
    if request.method == 'GET':
        try:
            sentence_number = request.session['sentence_number']
        except KeyError:
            sentence_number = 1

        r = run_user_kanshu(sentence_number, user, source_title_slug)
        context_dict['result_list'] = r['results']
        request.session['sides'] = r['sides']
        request.session['sentence_number'] = sentence_number

    if request.method == 'POST':
        sentence_number = request.POST['sentence_number'].strip()

        if sentence_number:
            # m = mother_text_helper(sentence_number)
            r = run_user_kanshu(sentence_number, user, source_title_slug)
            context_dict['result_list'] = r['results']
            request.session['sides'] = r['sides']
            request.session['sentence_number'] = sentence_number
            # request.session['mother_text'] = m

    kanshu_cookie_handler(request)
    context_dict['sides'] = request.session['sides']
    context_dict['sentence_number'] = request.session['sentence_number']
    context_dict['adjust'] = request.session['adjust']
    context_dict['source'] = source
    # context_dict['mother_text'] = request.session['mother_text']

    return render(request, 'rango/personal_kanshu.html', context=context_dict)

def user_index_cookie_handler(request):
    request.session['uservocabulary_list'] = get_server_side_cookie(request, 'uservocabulary_list', [])



def personal_kanshu_index_delete(request):
    context_dict = {}
    user = request.user
    source_list = UserSource.objects.filter(user=user)
    source_list = source_list.order_by('-title')
    print(source_list)
    context_dict['sources'] = source_list
    return render(request, 'rango/personal_kanshu_index_delete.html', context=context_dict)


def personal_kanshu_source_delete(request, source_title_slug):
    context_dict = {}
    user = request.user
    s = UserSource.objects.get(user=user, slug=source_title_slug)
    UserVocab.objects.filter(user=user, source=s).delete()
    s.delete()
                          #).sources.remove(s)

    source_list = UserSource.objects.filter(user=user)
    source_list = source_list.order_by('-title')
    context_dict['sources'] = source_list
    try:
        del request.session['uservocabulary_list']
    except KeyError:
        pass

    return render(request, 'rango/personal_kanshu_index_delete.html', context=context_dict)


def delete_session(request, sessName):
    try:
        del request.session[sessName]
    except KeyError:
        pass

@login_required
def personal_kanshu_index(request):

tango_with_django_project/templates/rango/add_category_old.html
{% extends 'rango/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Category</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                <div class="p-2"></div>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
            <div class="p-5"></div>
        </form>
    </div>
</div>


{% endblock %}

tango_with_django_project/templates/rango/base_old.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            Rango -
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
        {% block body_block %}
        {% endblock %}
        </div>
        <div> <!-- Sidebar block added. DM -->
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a></li>
                <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                <li><a href="{% url 'auth_password_change' %}">Change your Password</a></li>
            {% else %}
                <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
    </body>
</html>

tango_with_django_project/templates/rango/base_restricted.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Kanshu restricted
    </title>

   <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">



    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.21/af-2.3.5/b-1.6.2/b-colvis-1.6.2/b-flash-1.6.2/b-html5-1.6.2/b-print-1.6.2/cr-1.5.2/r-2.2.5/sc-2.0.2/sp-1.1.1/datatables.min.css"/>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css">


    <style type="text/css" class="init"></style>



    <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>



    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.print.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.5/js/dataTables.responsive.min.js"></script>
    <script type="text/javascript" class="init">
    $(document).ready(function() {
        $('.dataTable').DataTable({
                    pageLength: 500,
                    lengthMenu: [ 100, 200, 500, 1000, 5000, 10000 ],
                    paging: true,
                    searching: true,
                    columnDefs: [
                        { responsivePriority: 1, targets: 0 },
                        { responsivePriority: 10001, targets: 4 },
                        { responsivePriority: 2, targets: -2 }
                    ],
                    dom: 'Blfrtip',
                    buttons: [ 'copy', 'excel', 'print' ]
        });
    } );
    </script>

    <style id="holderjs-style" type="text/css"></style>

    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary p-0">
                <a class="navbar-brand p-2" href="{% url 'rango:cover' %}">Kanshu</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:contact_us' %}">Contact Us</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:kanshu_carousel' %}">Sample Book</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:personal_kanshu_index' %}">Dashboard*</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add a Dict.</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:kanshu_sentence' %}">KS</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:show_sentence' %}">Sentences</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' user.username %}">Your Profile</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>

        <a name="top"></a>

        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>

                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
                    {% block body_block %}{% endblock %}

                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#top" id="back-to-top">Back to top</a></p>
                        <p>&copy; 2020 Priyesh's Kanshu App &middot; </p>
<!--                            <a href="#">Privacy</a> &middot; <a href="#">Terms</a>-->
                    </footer>
                </main>
            </div>
        </div>

        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
<!--        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery.min.js"><\/script>')</script>-->
        <script src="{% static "js/rango-jquery.js" %}" crossorigin="anonymous"></script>
        <script src="{% static "js/rango-ajax.js" %}" crossorigin="anonymous"></script>









        <!--new-->


    </body>
</html>

tango_with_django_project/templates/rango/bootstrap-base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:bookshelf' %}">Bookshelf</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>

        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>

                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
                    {% block body_block %}{% endblock %}

                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2020 Priyesh's Kanshu App &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>

        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>

tango_with_django_project/templates/rango/categories.html
<ul class="nav flex-column">
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
                <span data-feather="archive"></span>{{ c.name }}
            </a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
                <span data-feather="archive"></span>{{ c.name }}
            </a>
        </li>
        {% endif %}
    {% endfor %}
{% else %}
    <li class="nav-item">There are no categories present.</li>
{% endif %}
</ul>

tango_with_django_project/templates/rango/contact_us.html
{% extends 'rango/base_bookshelf.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}

<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading"><center>Contact Us</center></h1>
        <div class="p-2"></div>
    </div>
</div>

<p class="float-right"><a href="#bottom">Go to bottom</a></p>


<div class="p-2"></div>


<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="p-2"></div>
    <input type="submit" value="Submit" />
</form>


<div class="p-2"></div>
<div class="p-2"></div>

<a name="bottom"></a>
{% endblock %}

tango_with_django_project/templates/rango/kanshu_carousel2.html
{% extends 'rango/kanshu_carousel.html' %}
{% load static %}